import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import type {Project} from '../src/data/projects';
import {indexCanvas,saveIndexLayout,indexProjects} from '../src/lib/index-layout';
import {EditorStore} from '../scripts/editor-store';
const group=(id:string,arrangement:'color'|'theme'='color'):Project=>({id,slug:id,title:id,arrangement,year:'',location:'',description:'',cover:id+'-photo',images:[{id:id+'-photo',src:'/test.jpg',width:200,height:300,alt:id}]});
test('INDEX order and leading, middle, trailing blanks persist independently of overview and other arrangement',async()=>{
  const data=[group('a'),group('b'),group('japan','theme')];
  const layout=[{kind:'blank',id:'blank-start',orientation:'portrait'},{kind:'photo',id:'b'},{kind:'blank',id:'blank-middle',orientation:'landscape'},{kind:'photo',id:'a'},{kind:'blank',id:'blank-end',orientation:'portrait'}];
  saveIndexLayout(data,'color',layout);
  assert.deepEqual(data.map(p=>p.id),['a','b','japan']);
  assert.deepEqual(indexProjects(data,'color').map(p=>p.id),['b','a']);
  assert.deepEqual(indexCanvas(data,'color').layout!.map(slot=>slot.kind==='photo'?slot.id:slot.orientation),['portrait','b','landscape','a','portrait']);
  assert.equal(data[2].indexCard,undefined);
  const before=JSON.stringify(data);
  assert.throws(()=>saveIndexLayout(data,'color',[{kind:'photo',id:'a'}]));
  assert.throws(()=>saveIndexLayout(data,'color',[{kind:'photo',id:'a'},{kind:'photo',id:'japan'}]));
  assert.equal(JSON.stringify(data),before);
  const root=await mkdtemp(join(tmpdir(),'bo-index-'));await mkdir(join(root,'src/data'),{recursive:true});
  await writeFile(join(root,'src/data/projects.json'),JSON.stringify(data));await writeFile(join(root,'src/data/image-manifest.json'),'{}');
  const store=new EditorStore(root),state=await store.snapshot();
  await store.saveIndex(state.revision,'color',[{kind:'photo',id:'a'},{kind:'photo',id:'b'}]);
  const reopened=await new EditorStore(root).snapshot();
  assert.deepEqual(indexCanvas(reopened.projects,'color').layout!.map(slot=>slot.id),['a','b']);
  await assert.rejects(store.saveIndex(state.revision,'color',layout),/另一个窗口/);
});
